"""Pre-computed template hashes for E2 template engine.

Each template is a SHA256 hash of a PII-replaced document sample.
When E2 processes a document, it replaces PII entities with type
placeholders, hashes the result, and checks against this library.

Templates are organized by document type for O(1) lookup.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class TemplateEntry:
    """A single template hash entry in the library.

    Attributes:
        template_hash: SHA256 hex digest of PII-replaced sample text.
        label: Document type this template represents.
        sample_count: How many samples contributed to this template.
        source: "builtin" (pre-computed) or "learned" (from customer data).
    """

    template_hash: str
    label: str
    sample_count: int = 1
    source: str = "builtin"


class TemplateLibrary:
    """In-memory template hash library with O(1) lookup.

    Usage:
        lib = TemplateLibrary()
        lib.add("abc123...", "HR & Payroll")
        result = lib.lookup("abc123...")  # → TemplateEntry or None
    """

    def __init__(self) -> None:
        self._templates: dict[str, TemplateEntry] = {}
        self._by_label: dict[str, list[str]] = {}

    def add(
        self, template_hash: str, label: str, source: str = "builtin"
    ) -> None:
        """Add or update a template hash entry.

        If the hash already exists with the same label, increment sample_count.
        """
        if template_hash in self._templates:
            existing = self._templates[template_hash]
            if existing.label == label:
                existing.sample_count += 1
            return

        entry = TemplateEntry(
            template_hash=template_hash,
            label=label,
            sample_count=1,
            source=source,
        )
        self._templates[template_hash] = entry
        self._by_label.setdefault(label, []).append(template_hash)

    def lookup(self, template_hash: str) -> TemplateEntry | None:
        """Look up a template hash. Returns None if not found."""
        return self._templates.get(template_hash)

    def partial_match(
        self, template_hash: str, prefix_len: int = 16
    ) -> TemplateEntry | None:
        """Look up by hash prefix (partial match fallback)."""
        for h, entry in self._templates.items():
            if h[:prefix_len] == template_hash[:prefix_len]:
                return entry
        return None

    def hashes_for_label(self, label: str) -> list[str]:
        """Return all template hashes for a given label."""
        return list(self._by_label.get(label, []))

    @property
    def count(self) -> int:
        return len(self._templates)

    @property
    def labels(self) -> list[str]:
        return sorted(self._by_label.keys())


# ── Builtin template library (pre-populated from sample documents) ──

BUILTIN_TEMPLATES = TemplateLibrary()

# All known document type labels — ensures the library is aware of every
# type even before real templates are loaded for a given label.
_BUILTIN_LABELS = [
    "HR & Payroll",
    "Financial Report",
    "Medical Record",
    "Legal Document",
    "API Log",
    "Technical Document",
    "Identity Document",
    "Email / Communication",
    "Government Form",
    "Education Record",
    "Real Estate Document",
    "Marketing Document",
    "Scientific Paper",
]

for _lbl in _BUILTIN_LABELS:
    BUILTIN_TEMPLATES._by_label.setdefault(_lbl, [])


def _bootstrap_builtin_templates() -> None:
    """Pre-computed template hashes from sample documents.

    These are PII-replaced SHA256 hashes of known document samples
    in output/sample_docs/.  Generated by bootstrap_templates.py.

    Key property: bootstrap and E2 runtime use the same
    PII-replacement logic (E2TemplateEngine._replace_pii), so a
    reproducible hash means a deterministic match.

    To regenerate after changing sample docs or PII_PATTERNS:
        cd impl-datadna && python bootstrap_templates.py
    """
    # --- finance_01: Quarterly Financial Report (PII: MONEY, CREDIT_CARD, IBAN)
    BUILTIN_TEMPLATES.add(
        "784a4a90f3a28ed4ab9c45606ffb1b7bd4567f853629437a220aaf0e0aff9601",
        "Financial Report", source="builtin",
    )

    # --- finance_02: Invoice (PII: MONEY, CREDIT_CARD)
    BUILTIN_TEMPLATES.add(
        "3948681175c3fd333b668d75b50bc05d8e57c021e308bf605a919428129c0367",
        "Financial Report", source="builtin",
    )

    # --- hr_01: Employee Record (PII: SSN)
    BUILTIN_TEMPLATES.add(
        "82dc9a89bd6a7e35052ac0d7969459d8f9a762b11c798bf3bcce3605ab59076d",
        "HR & Payroll", source="builtin",
    )

    # --- hr_02: New Hire Form (PII: SSN)
    BUILTIN_TEMPLATES.add(
        "2dadab47b414589f01f408cdac79b46d40be201ea2a4403f637f0b3a5b750ebe",
        "HR & Payroll", source="builtin",
    )

    # --- json_log_01: API JSON log (no PII detected — raw-text match)
    BUILTIN_TEMPLATES.add(
        "3bd0696b1bdf847460066d4dfcdb16085a01ebc7a31050fdd8e5f2c198aafb2d",
        "API Log", source="builtin",
    )

    # --- medical_01: Patient Record (PII: NPI)
    BUILTIN_TEMPLATES.add(
        "caba4b582af51b3524a30f445c2b3c6082e8d8ec4a6cceecb251cfe9eddc820e",
        "Medical Record", source="builtin",
    )

    # --- plain_01: Team Meeting Notes (no PII detected — raw-text match)
    BUILTIN_TEMPLATES.add(
        "18a969bc62fe257ba1727cb2fb65b3b5725d0607ed28fbd4af758e84598c56d3",
        "Email / Communication", source="builtin",
    )


_bootstrap_builtin_templates()
